CC=mingw32-gcc
CFLAGS=-Iinclude -DTRIMESH_LOADER_EXPORT

all: libtrimeshloader.a

clean:
	del /f src\tl3ds.o
	del /f src\tlobj.o
	del /f src\trimeshloader.o

libtrimeshloader.a: src/tl3ds.o src/tlobj.o src/trimeshloader.o
	ar -rus libtrimeshloader.a src/tl3ds.o src/tlobj.o src/trimeshloader.o
